services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      - db
    image: evageq/devops-for-programmers-project-74
    command: make test
  db:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_HOST: db
      POSTGRES_NAME: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password

